menu/urls.py
from django.urls import path 
from . import views
app_name = 'todo_app'

urlpatterns = [
    path('',views.HomePage.as_view(),name='index'),
    path('<int:pk>/',views.PostDetailView.as_view(),name = 'detail'),
    path('new/',views.CreateNewPost.as_view(),name='create'),
    path('delete/<int:pk>',views.deleteItem.as_view(),name='delete'),
    path('update/<int:pk>',views.updateItem.as_view(),name='update')
]

todo_list/urls.py
from django.contrib import admin
from django.urls import path,re_path
from menu import urls as todo_app
from django.conf.urls import include
urlpatterns = [
    path("admin/", admin.site.urls),
    path('',include(todo_app,namespace='todo_app')),
    re_path("",include('allauth.urls')),
]

menu/models.py
from django.db import models
from django.contrib.auth.models import User
class TodoApp(models.Model):
    title = models.CharField(max_length=100)
    text = models.TextField(null=True,blank=True)
    date = models.DateTimeField(auto_now=True)
    time = models.DateTimeField(null=True, blank=True)  
    author = models.ForeignKey(
        User,
        on_delete= models.CASCADE
    )
    def __str__(self) -> str:
        return self.title

menu/views.py
from django.views.generic import TemplateView,DetailView,DeleteView,CreateView,UpdateView
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import TodoApp
from django.shortcuts import render

class HomePage(TemplateView):
    template_name= 'menu/homepage.html'
    http_method_names = ['get']
    def dispatch(self, request, *args, **kwargs):
        self.request = request
        return super().dispatch(request, *args, **kwargs)
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        posts = TodoApp.objects.all().order_by('time')
        context['posts'] = posts 
        return context
    
class PostDetailView(DetailView):
    template_name = 'menu/detail.html'
    http_method_names = ['get']
    model = TodoApp
    context_object_name = 'post'
class CreateNewPost(LoginRequiredMixin,CreateView):
    template_name='menu/create.html'    
    success_url='/'
    model = TodoApp
    fields = ['title','text','time']
    def dispatch(self, request, *args, **kwargs):
        self.request = request
        return super().dispatch(request, *args, **kwargs)
    def form_valid(self,form):
        obj = form.save(commit=False)
        obj.author = self.request.user
        obj.save()
        return super().form_valid(form)
    def post(self,request,*args,**kwargs):
        post = TodoApp.objects.create(
            title = request.POST.get('title'),
            text = request.POST.get('text'),
            time = request.POST.get('time'),
            author = request.user,
        )
        return render(
            request,
            "include/post.html",
            {
            'post':post
            },
            content_type ="application/html"
        )
class deleteItem(DeleteView):
    template_name = 'menu/delete.html'
    model = TodoApp
    success_url = '/'
class updateItem(UpdateView):
    model = TodoApp
    template_name = 'menu/update.html'
    success_url= '/'
    fields= ['title','text','time']

menu/templates/menu/create.html
{%extends 'base.html' %}
{%block body%}
<div
        class="flex items-center justify-center fixed left-0 bottom-0 w-full h-full bg-gray-800 bg-opacity-75  js-modal">
        <div class="bg-white rounded-lg w-1/2">
          <div class="flex flex-col items-start p-4">
            <div class="flex items-center w-full">
              <div class="text-gray-900 font-medium text-lg">To do app</div>
              <svg class="ml-auto fill-current text-gray-700 w-6 h-6 cursor-pointer toggle-model"
                xmlns="http://www.w3.org/2000/svg" viewBox="0 0 18 18">
                <path
                  d="M14.53 4.53l-1.06-1.06L9 7.94 4.53 3.47 3.47 4.53 7.94 9l-4.47 4.47 1.06 1.06L9 10.06l4.47 4.47 1.06-1.06L10.06 9z" />
              </svg>
            </div>
            <hr>
            <div class="w-full">
              {# TODO: Add the ajax form #}
              <textarea class="border-2 border-blue-500 my-4 w-full js-post-title font-bold text-2xl" rows="1" placeholder="Enter your title"
                maxlength="100" data-post-url="{%url 'todo_app:create' %}"></textarea>
              <textarea class="border-2 border-blue-500 my-4 w-full js-post-text" rows="4" placeholder="Enter your post"
                maxlength="240" data-post-url="{%url 'todo_app:create' %}"></textarea>
                <input type="date" class="form-control js-post-time" id="date" data-post-url="{%url 'todo_app:create' %}">
            </div>
            <hr>
            <div class="ml-auto">
              <button
                class="bg-white text-gray-800 font-bold rounded border-b-2 border-green-500 hover:border-green-600 hover:bg-green-500 hover:text-white shadow-md py-1 px-3 inline-flex items-center text-sm mt-4 js-submit"
                type="button">
                <span class="mr-2">Create Post</span>
                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24">
                  <path fill="currentcolor" d="M2.01 21L23 12 2.01 3 2 10l15 2-15 2z"></path>
                </svg>
              </button>
            </div>
          </div>
        </div>
      </div>
     
{%endblock%}

menu/templates/menu/delete.html
{% extends 'base.html' %}
{% block body %}
    <form method ='POST' action=''>
        {% csrf_token %}
        <p>Do you want to delete this text</p>
        <button type="submit" class="btn btn-danger">Delete</button>
         <a href="/" class="btn btn-secondary">Cancel</a>
    </form>
{% endblock body %}

menu/templates/menu/detail.html
{% extends 'base.html' %}
{% block title %}{{post.text}}{% endblock  %}
{%block body%}
{%include 'include/post.html' with post=post  %}
{%endblock%}

menu/templates/menu/homepage.html
{%extends 'base.html' %}
{% block body %}
    {% for post in posts %}
    <div class="flex justify-center">
        {%include 'include/post.html' with post=post %}
    </div>
    {% endfor %}
{% endblock body %}

{% block style %}
    <style>
        header{
            backround: rgb(49,113,55);
            background: linear-gradient(0deg, rgba(49,113,55,1) 23%, rgba(55,83,52,1) 59%);
            width:100%;
            padding: 20px 40px;
            color: white;
            font-weight: 800;
            font-size: 30px;  
        }
    </style>
{% endblock style %}

menu/templates/menu/update.html
{% extends 'base.html' %}
{% load tailwind_filters %}
{% block body %}
    <form method='POST' action=''>
    {% csrf_token %}
    {{ form|crispy }}   
    <button class='p-5 bg-slate-600' type='submit'>Update</button>
    </form>
{% endblock body %}

todo_list/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title%}Django project {%endblock%}</title>
    <script src="https://cdn.tailwindcss.com"></script>
    {%block style%}
    {%endblock%}
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.4/jquery.min.js" integrity="sha512-pumBsjNRGGqkPzKHndZMaAG+bir374sORyzM3uulLV14lN5LyykqNk8eEeUlUkB3U0M4FApyaHraT65ihJhDpQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
</head>

<body>
    <nav class="bg-gray-800">
        <div class="mx-auto max-w-7xl px-2 sm:px-6 lg:px-8">
            <div class="relative flex h-16 items-center justify-between">
                <div class="absolute inset-y-0 left-0 flex items-center sm:hidden">


                    <svg class="block h-6 w-6" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor"
                        aria-hidden="true">
                        <path stroke-linecap="round" stroke-linejoin="round"
                            d="M3.75 6.75h16.5M3.75 12h16.5m-16.5 5.25h16.5" />
                    </svg>
                    <!--
                  Icon when menu is open.
      
                  Menu open: "block", Menu closed: "hidden"
                -->
                    <svg class="hidden h-6 w-6" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor"
                        aria-hidden="true">
                        <path stroke-linecap="round" stroke-linejoin="round" d="M6 18L18 6M6 6l12 12" />
                    </svg>
                    </button>
                </div>
                <div class="flex flex-1 items-center justify-center sm:items-stretch sm:justify-start">
                    
                    <div class="hidden sm:ml-6 sm:block">
                        <div class="flex space-x-4">
                            <!-- Current: "bg-gray-900 text-white", Default: "text-gray-300 hover:bg-gray-700 hover:text-white" -->
                            <a href="/"
                                class="bg-gray-700 text-white rounded-md px-3 py-2 text-sm font-medium hover:bg-gray-900"
                                aria-current="page">To-Do App</a>
                            <a href="{% url 'todo_app:create' %}"
                                class="bg-gray-700 text-white rounded-md px-3 py-2 text-sm font-medium hover:bg-gray-900"
                                aria-current="page">Create a message</a>

                        </div>
                    </div>
                </div>
                <div class="absolute inset-y-0 right-0 flex items-center pr-2 sm:static sm:inset-auto sm:ml-6 sm:pr-0">
                    <button type="button"
                        class="rounded-full bg-gray-800 p-1 text-gray-400 hover:text-white focus:outline-none focus:ring-2 focus:ring-white focus:ring-offset-2 focus:ring-offset-gray-800">
                        <span class="sr-only">View notifications</span>
                        <svg class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor"
                            aria-hidden="true">
                            <path stroke-linecap="round" stroke-linejoin="round"
                                d="M14.857 17.082a23.848 23.848 0 005.454-1.31A8.967 8.967 0 0118 9.75v-.7V9A6 6 0 006 9v.75a8.967 8.967 0 01-2.312 6.022c1.733.64 3.56 1.085 5.455 1.31m5.714 0a24.255 24.255 0 01-5.714 0m5.714 0a3 3 0 11-5.714 0" />
                        </svg>
                    </button>

                    <!-- Profile dropdown -->
                    {% if request.user.is_authenticated %}
                    <div class="relative ml-3 expand">
                        <div>
                            <button type="button"
                                class="flex rounded-full bg-gray-800 text-sm focus:outline-none focus:ring-2 focus:ring-white focus:ring-offset-2 focus:ring-offset-gray-800 "
                                id="user-menu-button" aria-expanded="false" aria-haspopup="true">
                                <span class="sr-only">Open user menu</span>
                                <img class="h-8 w-8 rounded-full"
                                    src="https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80"
                                    alt="">
                            </button>
                        </div>

                        <!--
                  Dropdown menu, show/hide based on menu state.
      
                  Entering: "transition ease-out duration-100"
                    From: "transform opacity-0 scale-95"
                    To: "transform opacity-100 scale-100"
                  Leaving: "transition ease-in duration-75"
                    From: "transform opacity-100 scale-100"
                    To: "transform opacity-0 scale-95"
                -->
                        <div class="absolute right-0 z-10 mt-2 w-48 origin-top-right rounded-md bg-white py-1 shadow-lg ring-1 ring-black ring-opacity-5 focus:outline-none hidden menu-profile"
                            role="menu" aria-orientation="vertical" aria-labelledby="user-menu-button" tabindex="-1">
                            <!-- Active: "bg-gray-100", Not Active: "" -->
                            <a href="#" class="block px-4 py-2 text-sm text-gray-700" role="menuitem" tabindex="-1"
                                id="user-menu-item-0">Your Profile</a>
                            <a href="#" class="block px-4 py-2 text-sm text-gray-700" role="menuitem" tabindex="-1"
                                id="user-menu-item-1">Settings</a>
                            <a href="{% url 'account_logout'%}" class="block px-4 py-2 text-sm text-gray-700" role="menuitem" tabindex="-1"
                                id="user-menu-item-2">Sign out</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        {%else %}
        <a href="{%url 'account_login'%}" class="flex items-center justify-center h-12 px-4 text-sm text-center text-gray-600 transition-colors duration-300 transform border rounded-lg xl:h-10 dark:text-gray-300 dark:border-gray-300 hover:bg-gray-100 dark:hover:bg-gray-700 focus:outline-none">
            Login
        </a>
        {%endif%}
        <!-- Mobile menu, show/hide based on menu state. -->

    </nav>

    {%block body%}
    {%endblock %}
    <script src="{% static 'js/main.js' %}"></script>

</body>

</html>

todo_list/templates/include/post.html
<div class="max-w-4xl px-10 my-4 py-6 bg-white rounded-lg shadow-md" style='width: 52rem'>
    <div class="flex justify-between items-center">
        <span class="font-light text-gray-600">{{ post.date|date:"F j, Y, g:i:a" }}</span>
    </div>
   
    <div class="mt-2">
        <p class="mt-2 text-gray-600 font-bold">{{ post.title }}</p>
        <p class="mt-2 text-gray-600">{{ post.text }}</p>

    </div>
    <div class="flex justify-between items-center mt-4">
        {% if show_detail_link %}
        <a class="text-blue-600 hover:underline" href="{% url 'todo_app:detail' post.id %}">
            {# TODO Add a detail url #}
            Read more
        </a>
        {% else %}
        <span>&nbsp;</span>
        {%endif%} 
        <div>
            {# TODO: User needs a link to their bio and a photo and a thumbnail and a name #}
           {% comment  %}
           <a class="flex items-center" href="{% url 'profiles:detail' post.author.username%}">
               {% thumbnail post.author.profile.image "100x100" crop="center" as im %}
               <img class="mx-4 w-10 h-10 object-cover rounded-full hidden sm:block" src="{{im.url}}" alt="avatar">
               {% endthumbnail %}
               
               <h1 class="text-gray-700 font-bold">{{post.author.username}}</h1>
           </a>
           {% endcomment %}
        </div>
    </div>
    <div class='text-blue'>
        <a href='{%url 'todo_app:delete' post.id%}'>Delete</a>
        <a href='{%url 'todo_app:update' post.id%}'>Update</a>
    </div>
</div>